[package]
name = "scratchers"
version = "0.1.0"
authors = ["Oleg Andreev <ooandreev@yandex-team.ru>"]
edition = "2018"

[profile.bench]
debug = true

[profile.release]
debug = true

[[bench]]
name = "audio"
harness = false

[[bench]]
name = "threadpool"
harness = false

[dependencies]
anyhow = "^1.0"
futures = { version = "^0.3", features = ["thread-pool"] }
hound = "^3.4"
num_cpus = "^1.13"
oddio = "^0.4"
parking_lot = "^0.11"
rayon = "^1.5"
# Waiting for 0.26
rg3d-sound = { git = "https://github.com/rg3dengine/rg3d/" }
rodio = "^0.14"
rubato = "^0.10"
samplerate = "^0.2"
sdl2 = { version = "^0.35", features = ["bundled"] }
# The version published at crates.io looks really old.
speexdsp-resampler = { git = "https://github.com/rust-av/speexdsp-rs", package = "speexdsp-resampler" }
tokio = { version = "^1.11", features = ["full"] }

[dev-dependencies]
criterion = "^0.3"

[patch.crates-io]
# Waiting until new release and version bump in rg3d-sound.
hrtf = { git = "https://github.com/mrDIMAS/hrtf/" }
