[package]
name = "scratchers"
version = "0.1.0"
authors = ["Oleg Andreev <ooandreev@yandex-team.ru>"]
edition = "2018"

[profile.bench]
debug = true

[profile.release]
debug = true

[[bench]]
name = "audio"
harness = false

[[bench]]
name = "threadpool"
harness = false

[dependencies]
ambisonic = "0.4"
futures = "0.3"
kira = "0.5"
hound = "3.4"
num_cpus = "1.13"
oddio = "0.4"
parking_lot = "0.11"
rayon = "1.5"
rg3d-sound = { git = "https://github.com/rg3dengine/rg3d", rev = "bd015ad" }
#rg3d-sound = "0.25"
rodio = "0.14"
soloud = "0.4"
tokio = { version = "1.10", features = ["full"] }

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }
