[package]
name = "scratchers"
version = "0.1.0"
authors = ["Oleg Andreev <ooandreev@yandex-team.ru>"]
edition = "2021"

[profile.bench]
debug = true

[profile.release]
debug = true

[[bench]]
name = "audio"
harness = false

[[bench]]
name = "matrix_mul"
harness = false

[[bench]]
name = "threadpool"
harness = false

[dependencies]
anyhow = "^1.0"
bytemuck = { version = "^1.7", features = ["derive"] }
crossbeam = "^0.8"
env_logger = "^0.9"
futures = { version = "^0.3", features = ["thread-pool"] }
glam = { version = "^0.20", features = ["bytemuck"] }
hound = "^3.4"
libc = "^0.2"
liquid = "^0.23"
log = "^0.4"
naga = { version = "^0.8", features = ["wgsl-in"] }
num_cpus = "^1.13"
oddio = "^0.4"
parking_lot = "^0.11"
rayon = "^1.5"
# Waiting for 0.26
rg3d-sound = { git = "https://github.com/rg3dengine/rg3d/", package = "rg3d-sound" }
rodio = "^0.14"
rubato = "^0.10"
samplerate = "^0.2"
sdl2 = { version = "^0.35", features = ["bundled"] }
# The version published at crates.io looks really old.
speexdsp-resampler = { git = "https://github.com/rust-av/speexdsp-rs", package = "speexdsp-resampler" }
tokio = { version = "^1.11", features = ["full"] }
wgpu = "^0.12"

[dev-dependencies]
criterion = "^0.3"

[build-dependencies]
anyhow = "^1.0"
glob = "^0.3"
cc = "^1.0"
env_logger = "^0.9"
log = "^0.4"

[features]
default = []
ispc = []

[patch.crates-io]
# Waiting until new release and version bump in rg3d-sound.
hrtf = { git = "https://github.com/mrDIMAS/hrtf/" }

wgpu-hal = { path = "vendor/wgpu-hal-0.12.0" }
