[package]
name = "scratchers"
version = "0.1.0"
authors = ["Oleg Andreev <ooandreev@yandex-team.ru>"]
edition = "2021"

[profile.bench]
debug = true

[profile.release]
debug = true

[[bench]]
name = "audio"
harness = false

[[bench]]
name = "matrix_mul"
harness = false

[[bench]]
name = "sparse_vec"
harness = false

[[bench]]
name = "threadpool"
harness = false

[dependencies]
anyhow = "^1.0"
bytemuck = { version = "^1.7", features = ["derive"] }
crossbeam = "^0.8"
env_logger = "^0.9"
erupt = { version = "^0.21", optional = true }
# Wait until 0.27
fyrox-sound = { git = "https://github.com/FyroxEngine/Fyrox", package = "fyrox-sound" }
futures = { version = "^0.3", features = ["thread-pool"] }
glam = { version = "^0.20", features = ["bytemuck"] }
gpu-alloc-erupt = { version = "^0.5", optional = true, features = ["tracing"] }
hound = "^3.4"
libc = "^0.2"
liquid = "^0.23"
log = "^0.4"
naga = { version = "^0.8", features = ["wgsl-in"] }
num_cpus = "^1.13"
oddio = "^0.5"
once_cell = "^1.9"
parking_lot = "^0.12"
rand = "^0.8"
rayon = "^1.5"
rodio = "^0.15"
rubato = "^0.10"
samplerate = "^0.2"
sdl2 = { version = "^0.35", features = ["bundled"] }
shaderc = { version = "^0.7", optional = true }
# The version published at crates.io looks really old.
speexdsp-resampler = { git = "https://github.com/rust-av/speexdsp-rs", package = "speexdsp-resampler" }
tokio = { version = "^1.11", features = ["full"] }
tracing = { version = "^0.1", optional = true }
wgpu = { version = "^0.12", optional = true }

[dev-dependencies]
criterion = "^0.3"
iai = "^0.1"

[build-dependencies]
anyhow = "^1.0"
glob = "^0.3"
cc = "^1.0"
env_logger = "^0.9"
log = "^0.4"

[features]
default = []
ispc = []
vulkan = ["erupt", "gpu-alloc-erupt", "shaderc", "tracing"]

[patch.crates-io]
wgpu-hal = { path = "vendor/wgpu-hal-0.12.0" }
