[package]
name = "xtask"
version = "0.1.0"
authors = ["Oleg Andreev <ooandreev@yandex-team.ru>"]
edition = "2021"

[dependencies]
anyhow = "^1.0"
clap = "^3.2"
dirs = "^4.0"
semver = "^1.0"
sha2 = "^0.10"
tempfile = "^3.2"
